# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  config.vm.boot_timeout = 60
  config.ssh.username = "ubuntu"

#### ANSIBLE
  config.vm.define "zape" do |zape|
    zape.vm.host_name = "zape"
    zape.vm.box = "zape"
    zape.vm.network "private_network", ip: "192.168.56.11", virtualbox__intnet: true, auto_config: true
  end

#### BASE
  config.vm.define "base" do |base|
    base.vm.host_name = "base"
    base.vm.box = "base"
    base.vm.network "private_network", ip: "192.168.56.12", virtualbox__intnet: true, auto_config: true
    base.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1", auto_correct: true
  end
end
