# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  config.vm.boot_timeout = 60

  config.vm.define "zipi" do |zipi|
    zipi.vm.host_name = "zipi"
    zipi.vm.box = "ubuntu/xenial64"
    zipi.vm.box_version = "20180306.0.0"
    zipi.vm.provision :shell, :path => "vagrant-bootstrap-base.sh"
    zipi.vm.provision :shell, :path => "vagrant-bootstrap-docker.sh"
    zipi.vm.provision :shell, :path => "vagrant-bootstrap-nagios_node.sh"
    zipi.vm.network "private_network", ip: "192.168.56.10", virtualbox__intnet: true, auto_config: true
  end

  config.vm.define "zape" do |zape|
    zape.vm.host_name = "zape"
    zape.vm.box = "ubuntu/xenial64"
    zape.vm.box_version = "20180306.0.0"
    zape.vm.provision :shell, :path => "vagrant-bootstrap-base.sh"
    zape.vm.provision :shell, :path => "vagrant-bootstrap-ansible.sh"
    zape.vm.provision :shell, :path => "vagrant-bootstrap-nagios_server.sh"
    zape.vm.network "private_network", ip: "192.168.56.11", virtualbox__intnet: true, auto_config: true
  end
end
