# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  config.vm.boot_timeout = 60

#  config.vm.define "base" do |base|
#    base.vm.host_name = "base"
#    base.vm.box = "ubuntu/xenial64"
#    base.vm.box_version = "20170331.0.0"
#    #base.vm.box_version = "20180306.0.0"
#    base.vm.provision :shell, :path => "vagrant-bootstrap-base.sh"
#    base.vm.network "private_network", ip: "192.168.56.12", virtualbox__intnet: true, auto_config: true
#  end

  config.vm.define "zipi" do |zipi|
    zipi.ssh.username = "ubuntu"
    zipi.vm.host_name = "zipi"
    zipi.vm.box = "ubuntu/xenial64"
    #zipi.vm.box_version = "20170331.0.0"
    zipi.vm.box_version = "20180306.0.0"
    #zipi.vm.box = "base"
    zipi.vm.provision :shell, :path => "vagrant-bootstrap-base.sh"
    zipi.vm.provision :shell, :path => "vagrant-bootstrap-zipi.sh"
    zipi.vm.network "private_network", ip: "192.168.56.10", virtualbox__intnet: true, auto_config: true
  end

  config.vm.define "zape" do |zape|
    zape.ssh.username = "ubuntu"
    zape.vm.host_name = "zape"
    zape.vm.box = "ubuntu/xenial64"
    #zape.vm.box_version = "20170331.0.0"
    zape.vm.box_version = "20180306.0.0"
    #zape.vm.box = "base"
    zape.vm.provision :shell, :path => "vagrant-bootstrap-base.sh"
    zape.vm.provision :shell, :path => "vagrant-bootstrap-zape.sh"
    zape.vm.network "private_network", ip: "192.168.56.11", virtualbox__intnet: true, auto_config: true
  end
end
