# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  config.vm.boot_timeout = 60
  config.ssh.username = "ubuntu"

#### JENKINS server - http://localhost:8081/
  config.vm.define "zipi" do |zipi|
    zipi.vm.host_name = "zipi"
    zipi.vm.box = "zipi"
    zipi.vm.network "private_network", ip: "192.168.56.10", virtualbox__intnet: true, auto_config: true
    zipi.vm.network "forwarded_port", guest: 8080, host: 8081, auto_correct: true
  end

#### JENKINS node
  config.vm.define "zape" do |zape|
    zape.vm.host_name = "zape"
    zape.vm.box = "base"
    zape.vm.network "private_network", ip: "192.168.56.11", virtualbox__intnet: true, auto_config: true
    zape.vm.network "forwarded_port", guest: 3000, host: 3000, auto_correct: true
  end
end
