# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
  end
  config.vm.boot_timeout = 60
  config.ssh.username = "ubuntu"
  
#### DOCKER
  config.vm.define "base" do |base|
    base.vm.host_name = "base"
    base.vm.box = "base"
    base.vm.network "private_network", ip: "192.168.32.12", virtualbox__intnet: true, auto_config: true
    base.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    base.vm.network "forwarded_port", guest: 8080, host: 8081, auto_correct: true
  end
end
